### ISSUE TITLE
tput use

### ISSUE THREAD

**Issue by periish** [Pan00Pernicek/nanofetch#4]
tput isn’t portable across platforms. Try tput setaf on freebsd

**Comment by Pan00Pernicek** [comment]
already fixed thanks to gk, yea tput doesnt work same as on linux bsd ~~i just installed linux's tput on bsd~~

**Comment by periish** [comment]
It’s not fixed in the bash version.

**Comment by Pan00Pernicek** [comment]
oh yeah i should fix that

**Comment by Pan00Pernicek** [comment]
i forgot i remove bash version
