### ISSUE TITLE
Compilation

### ISSUE THREAD

**Issue by safinsingh** [Pan00Pernicek/nanofetch#9]
Oh no! I'm having an error compiling `nanofetch.c` with `gcc`:

![Windows_Is_Awesome!!!](https://i.ibb.co/nPBcNXc/2020-10-11-21-04-33-Command-Prompt-gcc-nanocfetch-c.png)

Can you help me?

**Comment by Pan00Pernicek** [comment]
i didnt even starting on working on it, i currently have it just as placeholder until i will learn more of C
i will try work on it today
